# Generated by Django 3.0.5 on 2022-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/StudentProfilePic/'),
        ),
    ]
