# Generated by Django 3.0.5 on 2022-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_studentextra_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
